name: endeavour
version: '1.0.0'
synopsis: The central computing core for the USS Endeavour.
description: The central computing core for the USS Endeavour.
author: Colin Woodbury
maintainer: colingw@gmail.com
license: BSD3

extra-source-files:
  - ChangeLog.md

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds

dependencies:
  - base >=4.9 && <4.10
  - containers
  - freer-effects >=0.3 && <0.4
  - microlens >=0.4 && <0.5
  - microlens-aeson >=2.1 && <2.3
  - microlens-th >=0.4 && <0.5
  - optparse-generic >= 1.1 && < 1.2
  - sqlite-simple >=0.4 && <0.5
  - text >=1.2 && <1.3
  - time

library:
  source-dirs: endeavour
  dependencies:
    - aeson >=1.0 && <1.1
    - async >=2.1 && <2.2
    - fuzzy >=0.1 && <0.2
    - http-client >=0.5 && <0.6
    - http-client-tls >=0.3 && <0.4
    - servant >=0.9 && <0.10
    - servant-client >=0.9 && <0.10
    - shelly >=1.6 && <1.7
    - yaml >=0.8 && <0.9

tests:
  endeavour-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
      - -threaded
    dependencies:
      - endeavour
      - tasty >=0.10.1.2
      - tasty-hunit >=0.9.2

executables:
  endeavour-cli:
    main: Endeavour.hs
    source-dirs: endeavour-cli
    ghc-options:
      - -threaded
    dependencies:
      - async >= 2.1 && < 2.2
      - brick >= 0.15 && < 0.18
      - deque >= 0.2 && < 0.3
      - endeavour
      - microlens-platform >= 0.3 && < 0.4
      - th-printf >= 0.3 && < 0.4
      - unix
      - vector >= 0.11 && < 0.13
      - vty >= 5.15 && < 5.16

  endeavour-server:
    main: Endeavour.hs
    source-dirs: endeavour-server
    ghc-options:
      - -threaded
    dependencies:
      - endeavour
      - servant >=0.9 && <0.10
      - servant-server >=0.9 && <0.10
      - transformers
      - unix
      - warp >=3.2 && <3.3
