resolver: nightly-2016-10-15

packages:
  - './endeavour'
  - './endeavour-ai'

extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
