resolver: nightly-2016-12-01

packages:
  - './endeavour'
  - './endeavour-ai'

extra-deps:
  - 'fuzzy-0.1.0.0'

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
