resolver: nightly-2017-01-10

packages:
  - './endeavour'
  - './endeavour-server'
  - './endeavour-cli'

extra-deps:
  - 'deque-0.2'
  - 'dhall-1.0.1'
  - 'fuzzy-0.1.0.0'

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
